# Site settings
title: ET Thompson
email: shinkick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is about me. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yetihat.com" # the base hostname & protocol for your site
twitter_username: etthompson
github_username:  etthompson

# Build settings
markdown: kramdown
